name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    build: null
    needs: setup
    steps:
      - run: ./build_server.sh
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ./test_server.sh
      - name: my-step
        run: echo "Hello World!"
